name: diart
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - portaudio=19.6.*
  - pysoundfile=0.12.*
  - ffmpeg[version='<4.4']
  - pip
  - pip:
    - pyannote.audio  # Add this line
    - .  # This should remain as is if you're installing local packages
